# Generated by Django 3.2.9 on 2021-11-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cover',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.cover'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.pattern'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.size'),
        ),
    ]
